--[[
    Created by Slothpala 
--]]
local AB1 = function() return not MouseoverActionBars.db.profile.Module.ActionBar1 end
local AB2 = function() return not MouseoverActionBars.db.profile.Module.ActionBar2 end
local AB3 = function() return not MouseoverActionBars.db.profile.Module.ActionBar3 end
local AB4 = function() return not MouseoverActionBars.db.profile.Module.ActionBar4 end
local AB5 = function() return not MouseoverActionBars.db.profile.Module.ActionBar5 end
local AB6 = function() return not MouseoverActionBars.db.profile.Module.ActionBar6 end
local AB7 = function() return not MouseoverActionBars.db.profile.Module.ActionBar7 end
local AB8 = function() return not MouseoverActionBars.db.profile.Module.ActionBar8 end
local AB9 = function() return not MouseoverActionBars.db.profile.Module.ActionBar9 end
local AB10 = function() return not MouseoverActionBars.db.profile.Module.ActionBar10 end
local AB11 = function() return not MouseoverActionBars.db.profile.Module.ActionBar11 end

local options = {
    name = "MouseoverActionBars",
    handler = MouseoverActionBars,
    type = "group",
    childGroups = "tab",
    args = {
        ActionBars = {
            order = 1,
            name = "ActionBars",
            type = "group",
            args = {
                Config = {
                    order = 1,
                    name = "Enable for mosueover",
                    type = "group",
                    inline = true,
                    args = {
                        ActionBar1 = {
                            order = 1,
                            name = "AB1",
                            desc = "Action Bar 1",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.4,
                        },
                        ActionBar2 = {
                            order = 2,
                            name = "AB2",
                            desc = "Action Bar 2",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.4,
                        },
                        ActionBar3 = {
                            order = 3,
                            name = "AB3",
                            desc = "Action Bar 3",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.4,
                        },
                        ActionBar4 = {
                            order = 4,
                            name = "AB4",
                            desc = "Action Bar 4",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.4,
                        },
                        ActionBar5 = {
                            order = 5,
                            name = "AB5",
                            desc = "Action Bar 5",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.4,
                        },
                        ActionBar6 = {
                            order = 6,
                            name = "AB6",
                            desc = "Action Bar 6",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.4,
                        },
                        ActionBar7 = {
                            order = 7,
                            name = "AB7",
                            desc = "Action Bar 7",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.4,
                        },
                        ActionBar8 = {
                            order = 8,
                            name = "AB8",
                            desc = "Action Bar 8",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.4,
                        },
                        ActionBar9 = {
                            order = 9,
                            name = "Pet Bar",
                            desc = "Pet Bar",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.45,
                        },
                        ActionBar10 = {
                            order = 10,
                            name = "Stance Bar",
                            desc = "Stance Bar",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.6,
                        },
                        ActionBar11 = {
                            order = 11,
                            name = "Micro Menu",
                            desc = "Stance Bar",
                            type = "toggle",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.6,
                        },
                    },
                },
                AB1 = {
                    order = 2,
                    name = "Action Bar 1",
                    type = "group",
                    inline = true,
                    hidden = AB1,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the action bar fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,                        
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
                AB2 = {
                    order = 3,
                    name = "Action Bar 2",
                    type = "group",
                    inline = true,
                    hidden = AB2,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the action bars fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
                AB3 = {
                    order = 4,
                    name = "Action Bar 3",
                    type = "group",
                    inline = true,
                    hidden = AB3,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the action bars fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
                AB4 = {
                    order = 5,
                    name = "Action Bar 4",
                    type = "group",
                    inline = true,
                    hidden = AB4,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the action bars fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
                AB5 = {
                    order = 6,
                    name = "Action Bar 5",
                    type = "group",
                    inline = true,
                    hidden = AB5,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the action bars fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
                AB6 = {
                    order = 7,
                    name = "Action Bar 6",
                    type = "group",
                    inline = true,
                    hidden = AB6,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the action bars fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
                AB7 = {
                    order = 8,
                    name = "Action Bar 7",
                    type = "group",
                    inline = true,
                    hidden = AB7,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the action bars fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
                AB8 = {
                    order = 9,
                    name = "Action Bar 8",
                    type = "group",
                    inline = true,
                    hidden = AB8,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the action bars fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
                AB9 = {
                    order = 10,
                    name = "Pet Bar",
                    type = "group",
                    inline = true,
                    hidden = AB9,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the action bars fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
                AB10 = {
                    order = 11,
                    name = "Stance Bar",
                    type = "group",
                    inline = true,
                    hidden = AB10,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the action bars fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
                AB11 = {
                    order = 12,
                    name = "Micro Menu",
                    type = "group",
                    inline = true,
                    hidden = AB11,
                    args = {
                        fadeouttimer = {
                            order = 1,
                            name = "time to fade out",
                            desc = "timer after which the Micro Menu fades out",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            softMax = 10,   
                            step = 1,
                            width = 1.1,
                        },
                        minalpha = {
                            order = 2,
                            name = "min alpha",
                            desc = "the alpha value when your cursor leaves the region and the fadeouttimer passed",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                        maxalpha = {
                            order = 3,
                            name = "max alpha",
                            desc = "the alpha value when your cursor enters the region",
                            type = "range",
                            get = "GetStatus",
                            set = "SetStatus",
                            min = 0,
                            max = 1,   
                            isPercent = true,
                            step = 0.05,
                            width = 1.1,
                        },
                    },
                },
            },
        },      
        Config = {
            order = 2,
            name = "Config",
            type = "group",
            args = {
                Hide = {
                    order = 2,
                    name = "Hide",
                    type = "group",
                    inline = true,
                    args = {
                        HideBagsBar = {
                            order = 1,
                            type = "toggle",
                            name = "Bags Bar",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.55,
                        },
                        HideMicroMenu = {
                            order = 2,
                            type = "toggle",
                            name = "Micro Menu",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.7,
                        },
                        HideTrackingBars = {
                            order = 3,
                            type = "toggle",
                            desc = "XP and Reputation Bar",
                            name = "Tracking Bars",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.7,
                        },
                        HideStanceBar = {
                            order = 4,
                            type = "toggle",
                            name = "Stance Bar",
                            get = "GetModuleStatus",
                            set = "SetModuleStatus",
                            width = 0.7,
                        },
                    },
                },
                Combat = {
                    order = 3,
                    name = "Show during combat",
                    type = "group",
                    inline = true,
                    args = {
                        Combat1 = {
                            type = "toggle",
                            name = "AB1",
                            get = "GetStatus",
                            set = "SetStatus",
                            hidden = AB1,
                        },
                        Combat2 = {
                            type = "toggle",
                            name = "AB2",
                            get = "GetStatus",
                            set = "SetStatus",
                            hidden = AB2,
                        },
                        Combat3 = {
                            type = "toggle",
                            name = "AB3",
                            get = "GetStatus",
                            set = "SetStatus",
                            hidden = AB3,
                        },
                        Combat4 = {
                            type = "toggle",
                            name = "AB4",
                            get = "GetStatus",
                            set = "SetStatus",
                            hidden = AB4,
                        },
                        Combat5 = {
                            type = "toggle",
                            name = "AB5",
                            get = "GetStatus",
                            set = "SetStatus",
                            hidden = AB5,
                        },
                        Combat6 = {
                            type = "toggle",
                            name = "AB6",
                            get = "GetStatus",
                            set = "SetStatus",
                            hidden = AB6,
                        },
                        Combat7 = {
                            type = "toggle",
                            name = "AB7",
                            get = "GetStatus",
                            set = "SetStatus",
                            hidden = AB7,
                        },
                        Combat8 = {
                            type = "toggle",
                            name = "AB8",
                            get = "GetStatus",
                            set = "SetStatus",
                            hidden = AB8,
                        },
                        Combat9 = {
                            type = "toggle",
                            name = "Pet Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            hidden = AB9,
                        },
                        Combat10 = {
                            type = "toggle",
                            name = "Stance Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            hidden = AB10,
                        },
                    },
                },
                Exceptions = {
                    order = 4,
                    name = "Exceptions",
                    type = "group",
                    inline = true,
                    args = {
                        Dragonriding = {
                            order = 1,
                            type = "toggle",
                            name = "Dragonriding",
                            desc = "Always show Action Bar 1 while on a Dragonriding Mount",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 1,
                            hidden = AB1,
                        },
                    },
                },
            },
        }, 
        LinkedGroups = {
            order = 3,
            name = "Linked Action Bars",
            type = "group",
            args = {
                LinkedGroup1 = {
                    order = 1,
                    name = "Action Bar 1",
                    type = "group",
                    inline = true,
                    hidden = AB1,
                    args = {
                        ActionBar2 = {
                            type = "toggle",
                            desc = "",
                            name = "AB2",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB2,
                        },
                        ActionBar3 = {
                            type = "toggle",
                            desc = "",
                            name = "AB3",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB3,
                        },
                        ActionBar4 = {
                            type = "toggle",
                            desc = "",
                            name = "AB4",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB4,
                        },
                        ActionBar5 = {
                            type = "toggle",
                            desc = "",
                            name = "AB5",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB5,
                        },
                        ActionBar6 = {
                            type = "toggle",
                            desc = "",
                            name = "AB6",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB6,
                        },
                        ActionBar7 = {
                            type = "toggle",
                            desc = "",
                            name = "AB7",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB7,
                        },
                        ActionBar8 = {
                            type = "toggle",
                            desc = "",
                            name = "AB8",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB8,
                        },
                        ActionBar9 = {
                            type = "toggle",
                            desc = "",
                            name = "Pet Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.45,
                            hidden = AB9,
                        },
                        ActionBar10 = {
                            type = "toggle",
                            desc = "",
                            name = "Stance Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.55,
                            hidden = AB10,
                        },
                    },    
                },
                LinkedGroup2 = {
                    order = 2,
                    name = "Action Bar 2",
                    type = "group",
                    inline = true,
                    hidden = AB2,
                    args = {
                        ActionBar1 = {
                            type = "toggle",
                            desc = "",
                            name = "AB1",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB1,
                        },
                        ActionBar3 = {
                            type = "toggle",
                            desc = "",
                            name = "AB3",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB3,
                        },
                        ActionBar4 = {
                            type = "toggle",
                            desc = "",
                            name = "AB4",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB4,
                        },
                        ActionBar5 = {
                            type = "toggle",
                            desc = "",
                            name = "AB5",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB5,
                        },
                        ActionBar6 = {
                            type = "toggle",
                            desc = "",
                            name = "AB6",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB6,
                        },
                        ActionBar7 = {
                            type = "toggle",
                            desc = "",
                            name = "AB7",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB7,
                        },
                        ActionBar8 = {
                            type = "toggle",
                            desc = "",
                            name = "AB8",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB8,
                        },
                        ActionBar9 = {
                            type = "toggle",
                            desc = "",
                            name = "Pet Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.45,
                            hidden = AB9,
                        },
                        ActionBar10 = {
                            type = "toggle",
                            desc = "",
                            name = "Stance Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.55,
                            hidden = AB10,
                        },
                    },    
                },
                LinkedGroup3 = {
                    order = 3,
                    name = "Action Bar 3",
                    type = "group",
                    inline = true,
                    hidden = AB3,
                    args = {
                        ActionBar1 = {
                            type = "toggle",
                            desc = "",
                            name = "AB1",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB1,
                        },
                        ActionBar2 = {
                            type = "toggle",
                            desc = "",
                            name = "AB2",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB2,
                        },
                        ActionBar4 = {
                            type = "toggle",
                            desc = "",
                            name = "AB4",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB4,
                        },
                        ActionBar5 = {
                            type = "toggle",
                            desc = "",
                            name = "AB5",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB5,
                        },
                        ActionBar6 = {
                            type = "toggle",
                            desc = "",
                            name = "AB6",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB6,
                        },
                        ActionBar7 = {
                            type = "toggle",
                            desc = "",
                            name = "AB7",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB7,
                        },
                        ActionBar8 = {
                            type = "toggle",
                            desc = "",
                            name = "AB8",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB8,
                        },
                        ActionBar9 = {
                            type = "toggle",
                            desc = "",
                            name = "Pet Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.45,
                            hidden = AB9,
                        },
                        ActionBar10 = {
                            type = "toggle",
                            desc = "",
                            name = "Stance Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.55,
                            hidden = AB10,
                        },
                    },    
                },
                LinkedGroup4 = {
                    order = 4,
                    name = "Action Bar 4",
                    type = "group",
                    inline = true,
                    hidden = AB4,
                    args = {
                        ActionBar1 = {
                            type = "toggle",
                            desc = "",
                            name = "AB1",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB1,
                        },
                        ActionBar2 = {
                            type = "toggle",
                            desc = "",
                            name = "AB2",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB2,
                        },
                        ActionBar3 = {
                            type = "toggle",
                            desc = "",
                            name = "AB3",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB3,
                        },
                        ActionBar5 = {
                            type = "toggle",
                            desc = "",
                            name = "AB5",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB5,
                        },
                        ActionBar6 = {
                            type = "toggle",
                            desc = "",
                            name = "AB6",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB6,
                        },
                        ActionBar7 = {
                            type = "toggle",
                            desc = "",
                            name = "AB7",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB7,
                        },
                        ActionBar8 = {
                            type = "toggle",
                            desc = "",
                            name = "AB8",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB8,
                        },
                        ActionBar9 = {
                            type = "toggle",
                            desc = "",
                            name = "Pet Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.45,
                            hidden = AB9,
                        },
                        ActionBar10 = {
                            type = "toggle",
                            desc = "",
                            name = "Stance Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.55,
                            hidden = AB10,
                        },
                    },    
                },
                LinkedGroup5 = {
                    order = 5,
                    name = "Action Bar 5",
                    type = "group",
                    inline = true,
                    hidden = AB5,
                    args = {
                        ActionBar1 = {
                            type = "toggle",
                            desc = "",
                            name = "AB1",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB1,
                        },
                        ActionBar2 = {
                            type = "toggle",
                            desc = "",
                            name = "AB2",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB2,
                        },
                        ActionBar3 = {
                            type = "toggle",
                            desc = "",
                            name = "AB3",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB3,
                        },
                        ActionBar4 = {
                            type = "toggle",
                            desc = "",
                            name = "AB4",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB4,
                        },
                        ActionBar6 = {
                            type = "toggle",
                            desc = "",
                            name = "AB6",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB6,
                        },
                        ActionBar7 = {
                            type = "toggle",
                            desc = "",
                            name = "AB7",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB7,
                        },
                        ActionBar8 = {
                            type = "toggle",
                            desc = "",
                            name = "AB8",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB8,
                        },
                        ActionBar9 = {
                            type = "toggle",
                            desc = "",
                            name = "Pet Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.45,
                            hidden = AB9,
                        },
                        ActionBar10 = {
                            type = "toggle",
                            desc = "",
                            name = "Stance Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.55,
                            hidden = AB10,
                        },
                    },    
                },
                LinkedGroup6 = {
                    order = 6,
                    name = "Action Bar 6",
                    type = "group",
                    inline = true,
                    hidden = AB6,
                    args = {
                        ActionBar1 = {
                            type = "toggle",
                            desc = "",
                            name = "AB1",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB1,
                        },
                        ActionBar2 = {
                            type = "toggle",
                            desc = "",
                            name = "AB2",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB2,
                        },
                        ActionBar3 = {
                            type = "toggle",
                            desc = "",
                            name = "AB3",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB3,
                        },
                        ActionBar4 = {
                            type = "toggle",
                            desc = "",
                            name = "AB4",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB4,
                        },
                        ActionBar5 = {
                            type = "toggle",
                            desc = "",
                            name = "AB5",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB5,
                        },
                        ActionBar7 = {
                            type = "toggle",
                            desc = "",
                            name = "AB7",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB7,
                        },
                        ActionBar8 = {
                            type = "toggle",
                            desc = "",
                            name = "AB8",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB8,
                        },
                        ActionBar9 = {
                            type = "toggle",
                            desc = "",
                            name = "Pet Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.45,
                            hidden = AB9,
                        },
                        ActionBar10 = {
                            type = "toggle",
                            desc = "",
                            name = "Stance Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.55,
                            hidden = AB10,
                        },
                    },    
                },
                LinkedGroup7 = {
                    order = 7,
                    name = "Action Bar 7",
                    type = "group",
                    inline = true,
                    hidden = AB7,
                    args = {
                        ActionBar1 = {
                            type = "toggle",
                            desc = "",
                            name = "AB1",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB1,
                        },
                        ActionBar2 = {
                            type = "toggle",
                            desc = "",
                            name = "AB2",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB2,
                        },
                        ActionBar3 = {
                            type = "toggle",
                            desc = "",
                            name = "AB3",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB3,
                        },
                        ActionBar4 = {
                            type = "toggle",
                            desc = "",
                            name = "AB4",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB4,
                        },
                        ActionBar5 = {
                            type = "toggle",
                            desc = "",
                            name = "AB5",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB5,
                        },
                        ActionBar6 = {
                            type = "toggle",
                            desc = "",
                            name = "AB6",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB6,
                        },
                        ActionBar8 = {
                            type = "toggle",
                            desc = "",
                            name = "AB8",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB8,
                        },
                        ActionBar9 = {
                            type = "toggle",
                            desc = "",
                            name = "Pet Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.45,
                            hidden = AB9,
                        },
                        ActionBar10 = {
                            type = "toggle",
                            desc = "",
                            name = "Stance Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.55,
                            hidden = AB10,
                        },
                    },    
                },
                LinkedGroup8 = {
                    order = 8,
                    name = "Action Bar 8",
                    type = "group",
                    inline = true,
                    hidden = AB8,
                    args = {
                        ActionBar1 = {
                            type = "toggle",
                            desc = "",
                            name = "AB1",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB1,
                        },
                        ActionBar2 = {
                            type = "toggle",
                            desc = "",
                            name = "AB2",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB2,
                        },
                        ActionBar3 = {
                            type = "toggle",
                            desc = "",
                            name = "AB3",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB3,
                        },
                        ActionBar4 = {
                            type = "toggle",
                            desc = "",
                            name = "AB4",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB4,
                        },
                        ActionBar5 = {
                            type = "toggle",
                            desc = "",
                            name = "AB5",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB5,
                        },
                        ActionBar6 = {
                            type = "toggle",
                            desc = "",
                            name = "AB6",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB6,
                        },
                        ActionBar7 = {
                            type = "toggle",
                            desc = "",
                            name = "AB7",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB7,
                        },
                        ActionBar9 = {
                            type = "toggle",
                            desc = "",
                            name = "Pet Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.45,
                            hidden = AB9,
                        },
                        ActionBar10 = {
                            type = "toggle",
                            desc = "",
                            name = "Stance Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.55,
                            hidden = AB10,
                        },
                    },    
                },
                LinkedGroup9 = {
                    order = 9,
                    name = "Pet Bar",
                    type = "group",
                    inline = true,
                    hidden = AB9,
                    args = {
                        ActionBar1 = {
                            type = "toggle",
                            desc = "",
                            name = "AB1",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB1,
                        },
                        ActionBar2 = {
                            type = "toggle",
                            desc = "",
                            name = "AB2",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB2,
                        },
                        ActionBar3 = {
                            type = "toggle",
                            desc = "",
                            name = "AB3",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB3,
                        },
                        ActionBar4 = {
                            type = "toggle",
                            desc = "",
                            name = "AB4",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB4,
                        },
                        ActionBar5 = {
                            type = "toggle",
                            desc = "",
                            name = "AB5",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB5,
                        },
                        ActionBar6 = {
                            type = "toggle",
                            desc = "",
                            name = "AB6",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB6,
                        },
                        ActionBar7 = {
                            type = "toggle",
                            desc = "",
                            name = "AB7",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB7,
                        },
                        ActionBar8 = {
                            type = "toggle",
                            desc = "",
                            name = "AB8",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.45,
                        },
                        ActionBar10 = {
                            type = "toggle",
                            desc = "",
                            name = "Stance Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.55,
                            hidden = AB10,
                        },
                    },    
                },
                LinkedGroup10 = {
                    order = 10,
                    name = "Stance Bar",
                    type = "group",
                    inline = true,
                    hidden = AB10,
                    args = {
                        ActionBar1 = {
                            type = "toggle",
                            desc = "",
                            name = "AB1",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB1,
                        },
                        ActionBar2 = {
                            type = "toggle",
                            desc = "",
                            name = "AB2",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB2,
                        },
                        ActionBar3 = {
                            type = "toggle",
                            desc = "",
                            name = "AB3",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB3,
                        },
                        ActionBar4 = {
                            type = "toggle",
                            desc = "",
                            name = "AB4",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB4,
                        },
                        ActionBar5 = {
                            type = "toggle",
                            desc = "",
                            name = "AB5",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB5,
                        },
                        ActionBar6 = {
                            type = "toggle",
                            desc = "",
                            name = "AB6",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB6,
                        },
                        ActionBar7 = {
                            type = "toggle",
                            desc = "",
                            name = "AB7",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB7,
                        },
                        ActionBar8 = {
                            type = "toggle",
                            desc = "",
                            name = "AB8",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.33,
                            hidden = AB8,
                        },
                        ActionBar9 = {
                            type = "toggle",
                            desc = "",
                            name = "Pet Bar",
                            get = "GetStatus",
                            set = "SetStatus",
                            width = 0.45,
                            hidden = AB9,
                        },
                    },    
                },
            },
        },
    },
}


function MouseoverActionBars:GetOptionsTable()
    return options
end